n1=float(input("Número 1: "))
n2=float(input("Número 2: "))
n3=float(input("Número 3: "))
n4=float(input("Número 4: "))
media=(n1+n2+n3+n4)/4
maior= max(n1,n2,n3,n4)
menor= min(n1,n2,n3,n4)
diferenca= maior-menor
print(f"A média aritmética é: {media}", f"A diferença entre o maior e o menor valor é: {diferenca}", sep="\n")